### ISSUE TITLE
npm run dev failing

### ISSUE THREAD

**Issue by c0debreaker** [torontojs/torontojs.com#4]
Here is the error when I run it.

```
$ npm run dev

> torontojs.com@1.0.0 dev /private/tmp/torontojs.com
> babel-node devServer.js

/Users/bhavnanu/.nvm/versions/node/v4.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/logger.js:41
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /private/tmp/torontojs.com/devServer.js: Unknown option: base.stage
    at Logger.error (/Users/bhavnanu/.nvm/versions/node/v4.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/bhavnanu/.nvm/versions/node/v4.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    at OptionManager.init (/Users/bhavnanu/.nvm/versions/node/v4.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
    at File.initOptions (/Users/bhavnanu/.nvm/versions/node/v4.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/Users/bhavnanu/.nvm/versions/node/v4.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/Users/bhavnanu/.nvm/versions/node/v4.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Object.transformFileSync (/Users/bhavnanu/.nvm/versions/node/v4.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/api/node.js:116:10)
    at compile (/Users/bhavnanu/.nvm/versions/node/v4.2.2/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:102:20)
    at loader (/Users/bhavnanu/.nvm/versions/node/v4.2.2/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:130:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/bhavnanu/.nvm/versions/node/v4.2.2/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:140:7)

npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/bhavnanu/.nvm/versions/node/v4.2.2/bin/node" "/Users/bhavnanu/.nvm/versions/node/v4.2.2/bin/npm" "run" "dev"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! torontojs.com@1.0.0 dev: `babel-node devServer.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the torontojs.com@1.0.0 dev script 'babel-node devServer.js'.
npm ERR! This is most likely a problem with the torontojs.com package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node devServer.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls torontojs.com
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/torontojs.com/npm-debug.log
```

**Comment by tazsingh** [comment]
Do you have `babel-cli` installed globally?

This project uses Babel < 6 and it appears that you have `babel-cli` installed globally which is using Babel 6 and thus conflicting with Babel 5 in this project.

**Comment by c0debreaker** [comment]
Ah, that's what I thought too. I'm using 6. Thanks.

**Comment by c0debreaker** [comment]
btw, how were you able to tell I was using version 6? I'd like to know it so that next time I encounter this error, I know the cause. Thanks!

**Comment by tazsingh** [comment]
`babel-cli` isn't available for Babel 5 and it was in your stack trace :)

**Comment by c0debreaker** [comment]
Got it! Thanks :)
